# Folder where we want to store all the output files
out_folder: "../results/"
# File ending of the MAGS
mag_ending: ".fna"
# Folder of the MAGs. All the MAGs should end in `mag_ending`
input_folder: "../resources/tutorial_files/"
# Currently unused due to the fact the we do use the predicted media
medium: "../resources/tutorial_files/gf_medium.csv"
# Use the above specified medium or not not. Can be set to "true" or "false"
use_medium: "true"
# Keep list: Path to a list of MAG names that should be used in model building, ignored if ""
# This settings enables you to only build models for a subset of all bins specified in the input_folder
keep_list: ""
# If disabled the pipeline will pull the gapseq repo every time when the pipeline starts, additionally it will try to update the pipeline. This behaviour is troublesome with regards to reproducibility because running the pipeline at different time points for the same genome could produce different models.
skip_pull: True
